# Generated by Django 4.2.17 on 2025-01-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
